name: Terraform GCP - Env (Auto Plan + Apply)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: choice
        required: true
        options: [dev, stg, prod]

permissions:
  contents: read
  id-token: write

jobs:
  terraform_env:
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

      TF_VAR_bootstrap_project_id: ${{ secrets.TF_VAR_BOOTSTRAP_PROJECT_ID }}
      TF_VAR_org_id:               ${{ secrets.TF_VAR_ORG_ID }}
      TF_VAR_billing_account_id:   ${{ secrets.TF_VAR_BILLING_ACCOUNT_ID }}

      TFSTATE_BUCKET: "tfstate-bootstrap-project-487710"

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Authenticate to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_TERRAFORM_SA }}

      - name: Select env directory
        id: sel
        run: |
          ENV="${{ github.event.inputs.environment }}"
          echo "dir=terraform/gcp/env/$ENV" >> $GITHUB_OUTPUT
          echo "prefix=gcp/env/$ENV" >> $GITHUB_OUTPUT

      - name: Terraform init
        run: |
          terraform -chdir=${{ steps.sel.outputs.dir }} init \
            -backend-config="bucket=${TFSTATE_BUCKET}" \
            -backend-config="prefix=${{ steps.sel.outputs.prefix }}"

      - name: Terraform validate
        run: terraform -chdir=${{ steps.sel.outputs.dir }} validate

      - name: Terraform plan
        run: terraform -chdir=${{ steps.sel.outputs.dir }} plan -out=tfplan

      - name: Terraform apply
        run: terraform -chdir=${{ steps.sel.outputs.dir }} apply -auto-approve tfplan
