name: Terraform Snowflake - Manual (Plan + Apply)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: choice
        required: true
        options: [dev, stg, prod]

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

      TF_VAR_snowflake_organization_name: ${{ secrets.SNOWFLAKE_ORGANIZATION_NAME }}
      TF_VAR_snowflake_account_name:      ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
      TF_VAR_snowflake_username:          ${{ secrets.SNOWFLAKE_USERNAME }}
      TF_VAR_snowflake_password:          ${{ secrets.SNOWFLAKE_PASSWORD }}
      TF_VAR_svc_dbt_password:            ${{ secrets.SVC_DBT_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Check required TF vars are present
        run: |
          test -n "${TF_VAR_snowflake_organization_name}" || (echo "Missing SNOWFLAKE_ORGANIZATION_NAME" && exit 1)
          test -n "${TF_VAR_snowflake_account_name}"      || (echo "Missing SNOWFLAKE_ACCOUNT_NAME" && exit 1)
          test -n "${TF_VAR_snowflake_username}"          || (echo "Missing SNOWFLAKE_USERNAME" && exit 1)
          test -n "${TF_VAR_snowflake_password}"          || (echo "Missing SNOWFLAKE_PASSWORD" && exit 1)
          test -n "${TF_VAR_svc_dbt_password}"            || (echo "Missing SVC_DBT_PASSWORD" && exit 1)

      - name: Terraform fmt (auto)
        run: terraform fmt -recursive terraform/snowflake

      - name: Fail if formatting changed files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Terraform files were not formatted."
            echo "Please run locally: terraform fmt -recursive terraform/snowflake"
            git --no-pager diff
            exit 1
          fi

      - name: Terraform init (with backend)
        run: terraform -chdir=terraform/snowflake/envs/${{ github.event.inputs.environment }} init

      - name: Terraform validate
        run: terraform -chdir=terraform/snowflake/envs/${{ github.event.inputs.environment }} validate

      - name: Terraform plan
        run: terraform -chdir=terraform/snowflake/envs/${{ github.event.inputs.environment }} plan -out=tfplan

      - name: Terraform apply
        run: terraform -chdir=terraform/snowflake/envs/${{ github.event.inputs.environment }} apply -auto-approve tfplan